# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\2173452100291\Documents\CMMSApp\UI\UI_file\error_code_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error_Code_Management(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1325, 650)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.Group_cbb = QtWidgets.QComboBox(self.frame_5)
        self.Group_cbb.setObjectName("Group_cbb")
        self.horizontalLayout_4.addWidget(self.Group_cbb)
        self.horizontalLayout_5.addWidget(self.frame_5)

        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_9.setContentsMargins(9, 9, 9, 9)
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setObjectName(u"label_5")

        self.horizontalLayout_9.addWidget(self.label_5)

        self.Area_cbb = QtWidgets.QComboBox(self.frame_8)
        self.Area_cbb.setObjectName(u"Area_cbb")
        self.Area_cbb.setMinimumSize(QtCore.QSize(100, 0))

        self.horizontalLayout_9.addWidget(self.Area_cbb)


        self.horizontalLayout_5.addWidget(self.frame_8)

        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.Process_cbb = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Process_cbb.sizePolicy().hasHeightForWidth())
        self.Process_cbb.setSizePolicy(sizePolicy)
        self.Process_cbb.setObjectName("Process_cbb")
        self.horizontalLayout_6.addWidget(self.Process_cbb)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.Search_lnedit = QtWidgets.QLineEdit(self.frame_7)
        self.Search_lnedit.setObjectName("Search_lnedit")
        self.horizontalLayout_7.addWidget(self.Search_lnedit)
        self.horizontalLayout_5.addWidget(self.frame_7)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_5.addItem(spacerItem)
        self.Load_btn = QtWidgets.QPushButton(self.frame_3)
        self.Load_btn.setObjectName("Load_btn")
        self.horizontalLayout_5.addWidget(self.Load_btn)
        spacerItem1 = QtWidgets.QSpacerItem(525, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setBold(True)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.error_list_table = QtWidgets.QTableView(self.frame_13)
        self.error_list_table.setDragEnabled(False)
        self.error_list_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.error_list_table.setObjectName("error_list_table")
        self.verticalLayout_8.addWidget(self.error_list_table)
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.Insert_btn = QtWidgets.QPushButton(self.frame_14)
        self.Insert_btn.setObjectName(u"Insert_btn")
        self.Insert_btn.setMinimumSize(QtCore.QSize(100, 25))

        self.horizontalLayout_8.addWidget(self.Insert_btn)

        self.Delete_btn = QtWidgets.QPushButton(self.frame_14)
        self.Delete_btn.setObjectName(u"Delete_btn")
        self.Delete_btn.setMinimumSize(QtCore.QSize(100, 25))

        self.horizontalLayout_8.addWidget(self.Delete_btn)

        self.horizontalSpacer_3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        self.horizontalLayout_8.addItem(self.horizontalSpacer_3)


        self.verticalLayout_8.addWidget(self.frame_14)

        self.verticalLayout.addWidget(self.frame_13)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalSpacer_4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_4)

        self.Confirm_btn = QtWidgets.QPushButton(self.frame_4)
        self.Confirm_btn.setObjectName(u"Confirm_btn")
        self.Confirm_btn.setMinimumSize(QtCore.QSize(200, 30))
        self.Confirm_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))

        self.horizontalLayout_2.addWidget(self.Confirm_btn)

        self.Cancel_btn = QtWidgets.QPushButton(self.frame_4)
        self.Cancel_btn.setObjectName(u"Cancel_btn")
        self.Cancel_btn.setMinimumSize(QtCore.QSize(200, 30))
        self.Cancel_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))

        self.horizontalLayout_2.addWidget(self.Cancel_btn)

        self.horizontalSpacer_5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_5)


        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Error Code Management"))
        self.label.setText(_translate("Dialog", "Error Code Management"))
        self.label_2.setText(_translate("Dialog", "Group"))
        self.label_3.setText(_translate("Dialog", "Process"))
        self.label_4.setText(_translate("Dialog", "Search"))
        self.label_5.setText(_translate("Dialog", "Area"))
        self.Load_btn.setText(_translate("Dialog", "Load"))
        self.label_6.setText(_translate("Dialog", "Error Code List"))
        self.Insert_btn.setText(_translate("Dialog", "Insert"))
        self.Delete_btn.setText(_translate("Dialog", "Delete"))
        self.Confirm_btn.setText(_translate("Dialog", "Confirm"))
        self.Cancel_btn.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Error_Code_Management()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
