# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\2173452100291\Documents\CMMSApp\UI\UI_file\Filter_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)


def load_qss_file(qss_path):
    with open(qss_path, 'r', encoding='utf-8') as f:
        return f.read()

class Ui_Filter_frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Filter_frame")
        Frame.resize(200, 300)
        Frame.setStyleSheet('''
        QFrame#Filter_frame {
                background-color: #FFFFFF;
                border: 1px solid #E5E7EB;
                border-radius: 8px;
            }''')
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.code_frame = QtWidgets.QFrame(Frame)
        self.code_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.code_frame.setObjectName("code_frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.code_frame)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(self.code_frame)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.code_lnedit = QtWidgets.QLineEdit(self.code_frame)
        self.code_lnedit.setObjectName("code_lnedit")
        self.horizontalLayout_14.addWidget(self.code_lnedit)
        self.verticalLayout.addWidget(self.code_frame)
        self.name_frame = QtWidgets.QFrame(Frame)
        self.name_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.name_frame.setObjectName("name_frame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.name_frame)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_1 = QtWidgets.QLabel(self.name_frame)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_15.addWidget(self.label_1)
        self.name_lnedit = QtWidgets.QLineEdit(self.name_frame)
        self.name_lnedit.setObjectName("name_lnedit")
        self.horizontalLayout_15.addWidget(self.name_lnedit)
        self.verticalLayout.addWidget(self.name_frame)
        self.group_frame = QtWidgets.QFrame(Frame)
        self.group_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.group_frame.setObjectName("group_frame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.group_frame)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_2 = QtWidgets.QLabel(self.group_frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_17.addWidget(self.label_2)
        self.group_cbb = QtWidgets.QComboBox(self.group_frame)
        self.group_cbb.setObjectName("group_cbb")
        self.horizontalLayout_17.addWidget(self.group_cbb)
        self.verticalLayout.addWidget(self.group_frame)
        self.line_frame = QtWidgets.QFrame(Frame)
        self.line_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.line_frame.setObjectName("line_frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.line_frame)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_3 = QtWidgets.QLabel(self.line_frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_18.addWidget(self.label_3)
        self.line_cbb = QtWidgets.QComboBox(self.line_frame)
        self.line_cbb.setObjectName("line_cbb")
        self.horizontalLayout_18.addWidget(self.line_cbb)
        self.verticalLayout.addWidget(self.line_frame)
        self.status_frame = QtWidgets.QFrame(Frame)
        self.status_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.status_frame.setObjectName("status_frame")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.status_frame)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_4 = QtWidgets.QLabel(self.status_frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_19.addWidget(self.label_4)
        self.status_cbb = QtWidgets.QComboBox(self.status_frame)
        self.status_cbb.setObjectName("status_cbb")
        self.horizontalLayout_19.addWidget(self.status_cbb)
        self.verticalLayout.addWidget(self.status_frame)
        self.button_frame = QtWidgets.QFrame(Frame)
        self.button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.apply_filter_btn = QtWidgets.QPushButton(self.button_frame)
        self.apply_filter_btn.setFlat(False)
        self.apply_filter_btn.setObjectName("apply_filter_btn")
        self.horizontalLayout_21.addWidget(self.apply_filter_btn)
        self.cancel_filter_btn = QtWidgets.QPushButton(self.button_frame)
        self.cancel_filter_btn.setFlat(False)
        self.cancel_filter_btn.setObjectName("cancel_filter_btn")
        self.horizontalLayout_21.addWidget(self.cancel_filter_btn)
        self.verticalLayout.addWidget(self.button_frame)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Filter_frame", "Frame"))
        self.label.setText(_translate("Filter_frame", "Code"))
        self.label_1.setText(_translate("Filter_frame", "Name"))
        self.label_2.setText(_translate("Filter_frame", "Group"))
        self.label_3.setText(_translate("Filter_frame", "Line"))
        self.label_4.setText(_translate("Filter_frame", "Status"))
        self.apply_filter_btn.setText(_translate("Filter_frame", "Apply"))
        self.cancel_filter_btn.setText(_translate("Filter_frame", "Cancel"))

