# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\2173452100291\Documents\CMMSApp\UI\UI_file\OEE_mini_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

FONT_FAMILY = "Segoe UI"
COLOR_PRIMARY = "#0F4C81"   # Deep classic blue
COLOR_SUCCESS = "#2ECC71"   # Emerald Green (OEE >= 85%)
COLOR_WARNING = "#F1C40F"   # Sun Yellow (OEE 65% - 85%)
COLOR_DANGER = "#E74C3C"    # Alizarin Red (OEE < 65%)
COLOR_BG = "#F3F4F6"        # Neutral light background
COLOR_CARD_BG = "#FFFFFF"   # White cards
COLOR_TEXT_MAIN = "#1F2937" # Dark graphite
COLOR_TEXT_MUTED = "#6B7280"
COLOR_HOVER_BG = "#F7F7F7"
class Ui_OEE_mini_card(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.setFixedHeight(120)
        self.shadow = QtWidgets.QGraphicsDropShadowEffect(Frame)
        self.shadow.setBlurRadius(10)
        self.shadow.setColor(QtGui.QColor(0, 0, 0, 10))
        self.shadow.setOffset(0, 2)
        Frame.setGraphicsEffect(self.shadow)
        Frame.setStyleSheet(f"""
                            QFrame#Frame {{
                                background-color: {COLOR_CARD_BG};
                                border-radius: 12px;
                                border: 1px solid #E5E7EB;
                            }}
                            QFrame#Frame:hover {{
                                border: 3px solid #B44CFA;
                                background-color: {COLOR_HOVER_BG};
                            }}
                        """)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infor_widget = QtWidgets.QWidget(Frame)
        self.infor_widget.setObjectName("infor_widget")
        self.infor_widget.setFixedWidth(250)
        self.gridLayout = QtWidgets.QGridLayout(self.infor_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.line_lbl = QtWidgets.QLabel(self.infor_widget)
        self.line_lbl.setObjectName("line_lbl")
        self.line_lbl.setFont(QtGui.QFont(FONT_FAMILY, 15, QtGui.QFont.Bold))
        self.line_lbl.setStyleSheet(f"color: {COLOR_TEXT_MAIN}; border: none;")
        self.gridLayout.addWidget(self.line_lbl, 0, 0, 1, 1)
        self.model_lbl = QtWidgets.QLabel(self.infor_widget)
        self.model_lbl.setObjectName("model_lbl")
        self.model_lbl.setFont(QtGui.QFont(FONT_FAMILY, 13))
        self.model_lbl.setStyleSheet(f"color: {COLOR_TEXT_MUTED}; border: none;")
        self.gridLayout.addWidget(self.model_lbl, 1, 0, 1, 1)
        self.process_lbl = QtWidgets.QLabel(self.infor_widget)
        self.process_lbl.setObjectName("process_lbl")
        self.process_lbl.setFont(QtGui.QFont(FONT_FAMILY, 10))
        self.process_lbl.setStyleSheet(f"color: {COLOR_TEXT_MUTED}; border: none;")

        self.gridLayout.addWidget(self.process_lbl, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.infor_widget)
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setStyleSheet("background-color: #E5E7EB; max-width: 1px; border: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.OEE_chart = QtWidgets.QWidget(Frame)
        self.OEE_chart.setObjectName("OEE_chart")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OEE_chart.sizePolicy().hasHeightForWidth())
        self.OEE_chart.setSizePolicy(sizePolicy)
        self.OEE_chart.setMinimumWidth(150)
        # self.OEE_chart.setMaximumWidth(150)
        self.horizontalLayout.addWidget(self.OEE_chart)
        self.frame_2 = QtWidgets.QFrame(Frame)
        self.frame_2.setStyleSheet("background-color: #E5E7EB; max-width: 1px; border: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.metrics_widget = QtWidgets.QWidget(Frame)
        self.metrics_widget.setObjectName("metrics_widget")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metrics_widget.sizePolicy().hasHeightForWidth())
        self.metrics_widget.setSizePolicy(sizePolicy)
        self.metrics_widget.setMinimumWidth(350)
        self.metrics_layout = QtWidgets.QVBoxLayout(self.metrics_widget)
        self.metrics_layout.setContentsMargins(5, 0, 5, 0)
        self.metrics_layout.setSpacing(12)
        self.horizontalLayout.addWidget(self.metrics_widget)
        self.frame_4 = QtWidgets.QFrame(Frame)
        self.frame_4.setStyleSheet("background-color: #E5E7EB; max-width: 1px; border: none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.mttr_widget = QtWidgets.QWidget(Frame)
        self.mttr_widget.setObjectName(u"mttr_widget")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mttr_widget.sizePolicy().hasHeightForWidth())
        self.mttr_widget.setSizePolicy(sizePolicy)
        self.mttr_widget.setMinimumWidth(200)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mttr_widget)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label = QtWidgets.QLabel(self.mttr_widget)
        self.label.setObjectName(u"label")
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setFont(QtGui.QFont(FONT_FAMILY, 10, QtGui.QFont.Bold))
        self.label.setStyleSheet(f"color: {COLOR_TEXT_MAIN}; border: none;")
        self.label.setText("MTTR")
        self.verticalLayout_2.addWidget(self.label)

        self.mttr_chart = QtWidgets.QWidget(self.mttr_widget)
        self.mttr_chart.setObjectName(u"mttr_chart")
        self.mttr_chart_layout = QtWidgets.QVBoxLayout(self.mttr_chart)
        self.mttr_chart_layout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_2.addWidget(self.mttr_chart)


        self.horizontalLayout.addWidget(self.mttr_widget)

        self.frame_5 = QtWidgets.QFrame(Frame)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setStyleSheet(u"background-color: #E5E7EB; max-width: 1px; border: none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)

        self.horizontalLayout.addWidget(self.frame_5)

        self.mtbf_widget = QtWidgets.QWidget(Frame)
        self.mtbf_widget.setObjectName(u"mtbf_widget")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mtbf_widget.sizePolicy().hasHeightForWidth())
        self.mtbf_widget.setSizePolicy(sizePolicy)
        self.mtbf_widget.setMinimumWidth(200)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mtbf_widget)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QtWidgets.QLabel(self.mtbf_widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setFont(QtGui.QFont(FONT_FAMILY, 10, QtGui.QFont.Bold))
        self.label_2.setStyleSheet(f"color: {COLOR_TEXT_MAIN}; border: none;")
        self.label_2.setText("MTBF")
        self.verticalLayout.addWidget(self.label_2)

        self.mtbf_chart = QtWidgets.QWidget(self.mtbf_widget)
        self.mtbf_chart.setObjectName(u"mtbf_chart")

        self.verticalLayout.addWidget(self.mtbf_chart)
        self.mtbf_chart_layout = QtWidgets.QVBoxLayout(self.mtbf_chart)
        self.mtbf_chart_layout.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout.addWidget(self.mtbf_widget)
        self.horizontalSpacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        # self.horizontalLayout.addItem(self.horizontalSpacer)


        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Frame = QtWidgets.QFrame()
#     ui = Ui_Frame()
#     ui.setupUi(Frame)
#     Frame.show()
#     sys.exit(app.exec_())
