# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\2173452100291\Documents\CMMSApp\UI\UI_file\OEE_other_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os

def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)


def load_qss_file(qss_path):
    with open(qss_path, 'r', encoding='utf-8') as f:
        return f.read()
    
class UI_OEE_Other_Data(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("OEE_Other_Data")
        Dialog.resize(1200, 650)
        qss = load_qss_file(resource_path("Stylesheet/Ubuntu.qss"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.OEE_OD_groupBox_4 = QtWidgets.QGroupBox(self.frame_3)
        self.OEE_OD_groupBox_4.setObjectName(u"OEE_OD_groupBox_4")
        self.OEE_OD_groupBox_4.setStyleSheet(qss)
        self.OEE_OD_groupBox_4.setFont(font)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.OEE_OD_groupBox_4)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.OEE_OD_area_cbb = QtWidgets.QComboBox(self.OEE_OD_groupBox_4)
        self.OEE_OD_area_cbb.setObjectName(u"OEE_OD_area_cbb")
        self.OEE_OD_area_cbb.setMinimumSize(QtCore.QSize(100, 0))
        self.horizontalLayout_10.addWidget(self.OEE_OD_area_cbb)
        self.horizontalLayout_3.addWidget(self.OEE_OD_groupBox_4)

        self.OEE_OD_groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.OEE_OD_groupBox_3.setObjectName("OEE_OD_groupBox_3")
        self.OEE_OD_groupBox_3.setStyleSheet(qss)
        self.OEE_OD_groupBox_3.setFont(font)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.OEE_OD_groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.OEE_OD_model_cbb = QtWidgets.QComboBox(self.OEE_OD_groupBox_3)
        self.OEE_OD_model_cbb.setMinimumSize(QtCore.QSize(100, 0))
        self.OEE_OD_model_cbb.setObjectName("OEE_OD_model_cbb")
        self.horizontalLayout_4.addWidget(self.OEE_OD_model_cbb)
        self.horizontalLayout_3.addWidget(self.OEE_OD_groupBox_3)
        self.OEE_OD_groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.OEE_OD_groupBox.setObjectName("OEE_OD_groupBox")
        self.OEE_OD_groupBox.setStyleSheet(qss)
        self.OEE_OD_groupBox.setFont(font)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.OEE_OD_groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.OEE_OD_line_cbb = QtWidgets.QComboBox(self.OEE_OD_groupBox)
        self.OEE_OD_line_cbb.setMinimumSize(QtCore.QSize(100, 0))
        self.OEE_OD_line_cbb.setObjectName("OEE_OD_line_cbb")
        self.horizontalLayout_5.addWidget(self.OEE_OD_line_cbb)
        self.horizontalLayout_3.addWidget(self.OEE_OD_groupBox)
        self.OEE_OD_groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.OEE_OD_groupBox_2.setObjectName("OEE_OD_groupBox_2")
        self.OEE_OD_groupBox_2.setStyleSheet(qss)
        self.OEE_OD_groupBox_2.setFont(font)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.OEE_OD_groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.OEE_OD_period_edit = QtWidgets.QDateEdit(self.OEE_OD_groupBox_2)
        self.OEE_OD_period_edit.setMinimumSize(QtCore.QSize(100, 0))
        self.OEE_OD_period_edit.setReadOnly(False)
        self.OEE_OD_period_edit.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 12, 1), QtCore.QTime(0, 0, 0)))
        self.OEE_OD_period_edit.setCalendarPopup(True)
        self.OEE_OD_period_edit.setObjectName("OEE_OD_period_edit")
        self.OEE_OD_period_edit.setAccelerated(False)
        self.OEE_OD_period_edit.setProperty("showGroupSeparator", False)
        self.OEE_OD_calendar_widget = self.OEE_OD_period_edit.calendarWidget()
        self.OEE_OD_calendar_widget.setStyleSheet("""
                                                QCalendarWidget QWidget#qt_calendar_navigationbar {
                                                        background-color: #0066cc; /* Màu xanh nền */
                                                }
                                                QCalendarWidget QToolButton {
                                                        color: white;
                                                        font-weight: bold;
                                                        background-color: transparent;
                                                }
                                                """
                                               )
        self.OEE_OD_period_edit.setDisplayFormat("MMM-yyyy")
        self.table_view_of_DTcalendar = self.OEE_OD_calendar_widget.findChild(
            QtWidgets.QTableView)
        self.table_view_of_DTcalendar.hide()
        self.OEE_OD_calendar_widget.setFixedSize(250, 30)
        self.horizontalLayout_6.addWidget(self.OEE_OD_period_edit)
        self.horizontalLayout_3.addWidget(self.OEE_OD_groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_3)
        self.Tab_widget = QtWidgets.QTabWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Tab_widget.setFont(font)
        self.Tab_widget.setTabPosition(QtWidgets.QTabWidget.West)
        self.Tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tab_widget.setDocumentMode(False)
        self.Tab_widget.setTabsClosable(False)
        self.Tab_widget.setMovable(False)
        self.Tab_widget.setTabBarAutoHide(False)
        self.Tab_widget.setObjectName("Tab_widget")
        self.cycle_time_tab = QtWidgets.QWidget()
        self.cycle_time_tab.setObjectName("cycle_time_tab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.cycle_time_tab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.machine_cycle_table = QtWidgets.QTableView(self.cycle_time_tab)
        self.machine_cycle_table.setObjectName("machine_cycle_table")
        self.machine_cycle_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.machine_cycle_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.machine_cycle_table.setWordWrap(True)
        self.horizontalLayout_7.addWidget(self.machine_cycle_table)
        self.Tab_widget.addTab(self.cycle_time_tab, "")
        self.operation_time_tab = QtWidgets.QWidget()
        self.operation_time_tab.setObjectName("operation_time_tab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.operation_time_tab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.line_operation_table = QtWidgets.QTableView(self.operation_time_tab)
        self.line_operation_table.setObjectName("line_operation_table")
        self.line_operation_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.line_operation_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.line_operation_table.setWordWrap(True)
        self.line_operation_table.verticalHeader().setVisible(False)
        self.horizontalLayout_8.addWidget(self.line_operation_table)
        self.Tab_widget.addTab(self.operation_time_tab, "")
        self.verticalLayout.addWidget(self.Tab_widget)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.confirm_btn = QtWidgets.QPushButton(self.frame_2)
        self.confirm_btn.setObjectName("confirm_btn")
        self.horizontalLayout_2.addWidget(self.confirm_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.frame_2)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        self.Tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("OEE_Other_Data", "OEE Other Data"))
        self.label.setText(_translate("OEE_Other_Data", "Other Data"))
        self.OEE_OD_groupBox_4.setTitle(_translate("OEE_Other_Data", "Area"))
        self.OEE_OD_groupBox_3.setTitle(_translate("OEE_Other_Data", "Model"))
        self.OEE_OD_groupBox.setTitle(_translate("OEE_Other_Data", "Line"))
        self.OEE_OD_groupBox_2.setTitle(_translate("OEE_Other_Data", "Period"))
        self.Tab_widget.setTabText(self.Tab_widget.indexOf(self.cycle_time_tab), _translate("OEE_Other_Data", "Machine Cycle Time"))
        self.Tab_widget.setTabText(self.Tab_widget.indexOf(self.operation_time_tab), _translate("OEE_Other_Data", "Line Operation Times"))
        self.confirm_btn.setText(_translate("OEE_Other_Data", "Confirm"))
        self.cancel_btn.setText(_translate("OEE_Other_Data", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UI_OEE_Other_Data()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
