# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\2173452100291\Documents\CMMSApp\UI\UI_file\OEE_Edit_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)


def load_qss_file(qss_path):
    with open(qss_path, 'r', encoding='utf-8') as f:
        return f.read()

class SuffixLineEdit(QtWidgets.QLineEdit):
    def __init__(self, parent=None, suffix_text=""):
        super().__init__(parent)
        self.suffix_label = QtWidgets.QLabel(suffix_text, self)
        self.suffix_label.setStyleSheet("color: #888888; background: transparent;") 
        
        internal_layout = QtWidgets.QHBoxLayout(self)
        internal_layout.addStretch() 
        internal_layout.addWidget(self.suffix_label)
        
        internal_layout.setContentsMargins(0, 0, 10, 0)
        internal_layout.setAlignment(QtCore.Qt.AlignVCenter)

        if suffix_text:
            self.setSuffix(suffix_text)

    def setSuffix(self, text):
        self.suffix_label.setText(text)
        self.suffix_label.adjustSize() 
        right_margin = self.suffix_label.width() + 15
        self.setTextMargins(0, 0, right_margin, 0)

class UI_OEE_Edit_Data(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("OEE_Edit_Data")
        Dialog.resize(550, 500)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        qss = load_qss_file(resource_path("Stylesheet\\Ubuntu.qss"))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.OEEsub_groupBox = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.OEEsub_groupBox.setFont(font)
        self.OEEsub_groupBox.setObjectName("OEEsub_groupBox")
        self.OEEsub_groupBox.setStyleSheet(qss)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.OEEsub_groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.working_shift_lnedit = SuffixLineEdit(self.OEEsub_groupBox)
        self.working_shift_lnedit.setObjectName("working_shift_lnedit")
        self.horizontalLayout_2.addWidget(self.working_shift_lnedit)
        self.verticalLayout_3.addWidget(self.OEEsub_groupBox)
        self.OEEsub_groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.OEEsub_groupBox_2.setFont(font)
        self.OEEsub_groupBox_2.setObjectName("OEEsub_groupBox_2")
        self.OEEsub_groupBox_2.setStyleSheet(qss)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OEEsub_groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.downtime_records_widget = QtWidgets.QListWidget(self.OEEsub_groupBox_2)
        self.downtime_records_widget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.downtime_records_widget.setObjectName("downtime_records_widget")
        self.verticalLayout_2.addWidget(self.downtime_records_widget)
        self.verticalLayout_3.addWidget(self.OEEsub_groupBox_2)
        self.OEEsub_groupBox_3 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.OEEsub_groupBox_3.setFont(font)
        self.OEEsub_groupBox_3.setObjectName("OEEsub_groupBox_3")
        self.OEEsub_groupBox_3.setStyleSheet(qss)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.OEEsub_groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FGs_lnedit = SuffixLineEdit(self.OEEsub_groupBox_3)
        self.FGs_lnedit.setObjectName("FGs_lnedit")
        self.horizontalLayout_3.addWidget(self.FGs_lnedit)
        self.verticalLayout_3.addWidget(self.OEEsub_groupBox_3)
        self.OEEsub_groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.OEEsub_groupBox_4.setFont(font)
        self.OEEsub_groupBox_4.setObjectName("OEEsub_groupBox_4")
        self.OEEsub_groupBox_4.setStyleSheet(qss)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.OEEsub_groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.defect_lnedit = SuffixLineEdit(self.OEEsub_groupBox_4)
        self.defect_lnedit.setObjectName("defect_lnedit")
        self.horizontalLayout_4.addWidget(self.defect_lnedit)
        self.verticalLayout_3.addWidget(self.OEEsub_groupBox_4)
        self.horizontalLayout.addWidget(self.frame_2)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.setMaximumHeight(35)
        self.verticalLayout_4.addWidget(self.label_2)
        self.result_table = QtWidgets.QTableView(self.frame_3)
        self.result_table.setObjectName("result_table")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_table.sizePolicy().hasHeightForWidth())
        self.result_table.setSizePolicy(sizePolicy)
        self.result_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.result_table.setWordWrap(True)
        self.result_table.horizontalHeader().setVisible(False)
        self.result_table.horizontalHeader().setHighlightSections(False)
        self.result_table.verticalHeader().setVisible(False)
        self.result_table.verticalHeader().setHighlightSections(False)
        self.result_table.setAlternatingRowColors(True)
        self.result_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.result_table.setStyleSheet(qss)
        self.verticalLayout_4.addWidget(self.result_table)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit OEE Data"))
        self.label.setText(_translate("Dialog", "OEE Data Edit"))
        self.OEEsub_groupBox.setTitle(_translate("Dialog", "Working Shift"))
        self.OEEsub_groupBox_2.setTitle(_translate("Dialog", "Downtime Records"))
        self.OEEsub_groupBox_3.setTitle(_translate("Dialog", "FGs Output"))
        self.OEEsub_groupBox_4.setTitle(_translate("Dialog", "Defect"))
        self.label_2.setText(_translate("Dialog", "Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UI_OEE_Edit_Data()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
