# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\2173452100291\Documents\OEE_project\UI\UI_file\Print_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os

def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

def load_qss_file(qss_path):
    with open(qss_path, 'r', encoding='utf-8') as f:
            return f.read()

class Ui_print_selector(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 213)
        qss = load_qss_file(resource_path("Stylesheet\\Ubuntu.qss"))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Print_main_frame = QtWidgets.QFrame(Form)
        self.Print_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Print_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Print_main_frame.setObjectName("Print_main_frame")
        self.Print_main_frame.setStyleSheet(qss)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Print_main_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.Print_main_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.Print_main_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Print_select_cbb = QtWidgets.QComboBox(self.frame_3)
        self.Print_select_cbb.setMinimumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(75)
        self.Print_select_cbb.setFont(font)
        self.Print_select_cbb.setObjectName("Print_select_cbb")
        self.horizontalLayout.addWidget(self.Print_select_cbb)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.Print_main_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.Print_main_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Print_confirm_bt = QtWidgets.QPushButton(self.frame_4)
        self.Print_confirm_bt.setMinimumSize(QtCore.QSize(0, 30))
        self.Print_confirm_bt.setObjectName("Print_confirm_bt")
        self.horizontalLayout_2.addWidget(self.Print_confirm_bt)
        self.Print_cancel_bt = QtWidgets.QPushButton(self.frame_4)
        self.Print_cancel_bt.setMinimumSize(QtCore.QSize(0, 30))
        self.Print_cancel_bt.setObjectName("Print_cancel_bt")
        self.horizontalLayout_2.addWidget(self.Print_cancel_bt)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.Print_main_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Select Printer Model"))
        self.label_2.setText(_translate("Form", "Printer"))
        self.label_3.setText(_translate("Form", "Quantity:"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.Print_confirm_bt.setText(_translate("Form", "Confirm"))
        self.Print_cancel_bt.setText(_translate("Form", "Cancel"))

