# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\2173452100291\Documents\OEE_project\UI\UI_file\Sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys
def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)
    
def load_qss_file(qss_path):
        with open(qss_path, 'r', encoding='utf-8') as f:
            return f.read()
        
class Ui_Login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("CMMS system")
        Dialog.resize(470, 378)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        qss = load_qss_file(resource_path("Stylesheet\\Ubuntu.qss"))
        self.Signin_widget = QtWidgets.QWidget(Dialog)
        self.Signin_widget.setGeometry(QtCore.QRect(0, 0, 811, 551))
        self.Signin_widget.setStyleSheet("background: #fafafa")
        self.Signin_widget.setObjectName("Signin_widget")
        self.label = QtWidgets.QLabel(self.Signin_widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 421, 351))
        effect = QtWidgets.QGraphicsOpacityEffect()
        effect.setOpacity(0.2)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(resource_path("Icons/Tokin-logo.png")))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setGraphicsEffect(effect)
        self.label_2 = QtWidgets.QLabel(self.Signin_widget)
        self.label_2.setGeometry(QtCore.QRect(165, 10, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(56)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.signin_frame = QtWidgets.QFrame(self.Signin_widget)
        self.signin_frame.setGeometry(QtCore.QRect(20, 70, 431, 241))
        self.signin_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signin_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signin_frame.setObjectName("signin_frame")
        self.signin_frame.setStyleSheet(""" #signin_frame {
                                                            border: 2px solid rgba(0, 0, 255, 0.1);                          
                                                            border-radius: 15px;
                                                            background-color: white;
                                                            }""")
        effect.setOpacity(0.95)
        self.signin_frame.setGraphicsEffect(effect)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.signin_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.login_btn =  QtWidgets.QPushButton(self.Signin_widget)
        self.login_btn.setObjectName(u"login_btn")
        self.login_btn.setGeometry(QtCore.QRect(165, 320, 121, 41))
        self.login_btn.setText("LOG IN")
        self.login_btn.setStyleSheet(qss)
        self.user_frame = QtWidgets.QFrame(self.signin_frame)
        self.user_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_frame.setObjectName("user_frame")
        self.user_frame.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.user_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.user_frame)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        font1 = QtGui.QFont()
        font1.setFamily(u"Segoe UI Semibold")
        font1.setPointSize(16)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_3.setFont(font1)

        self.horizontalLayout_2.addWidget(self.label_3)

        self.user_status = QtWidgets.QLabel(self.frame)
        self.user_status.setObjectName(u"user_status")

        self.horizontalLayout_2.addWidget(self.user_status)


        self.verticalLayout.addWidget(self.frame)
        
        self.user_line = QtWidgets.QLineEdit(self.user_frame)
        self.user_line.setObjectName("user_line")
        self.user_line.setFixedSize(QtCore.QSize(400,50))
        self.user_line.setStyleSheet(qss)
        self.verticalLayout.addWidget(self.user_line)
        self.verticalLayout_4.addWidget(self.user_frame)
        self.password_frame = QtWidgets.QFrame(self.signin_frame)
        self.password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_frame.setObjectName("password_frame")
        self.password_frame.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.password_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.password_frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font1)

        self.horizontalLayout_3.addWidget(self.label_4)

        self.pass_status = QtWidgets.QLabel(self.frame_2)
        self.pass_status.setObjectName(u"pass_status")

        self.horizontalLayout_3.addWidget(self.pass_status)


        self.verticalLayout_3.addWidget(self.frame_2)
        self.password_line = QtWidgets.QLineEdit(self.password_frame)
        self.password_line.setObjectName("password_line")
        self.password_line.setFixedSize(QtCore.QSize(400,50))
        self.password_line.setStyleSheet(qss)
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayout_3.addWidget(self.password_line)
        self.verticalLayout_4.addWidget(self.password_frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("CMMS system", "CMMS system"))
        self.label_2.setText(_translate("Dialog", "Sign In"))
        self.label_3.setText(_translate("Dialog", "User name"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.login_btn.setText(_translate("Dialog", "LOG IN"))

# if __name__ == "__main__":
#     app = QtWidgets.QApplication(sys.argv)
#     window = Ui_Login()
#     window.show()
#     app.exec_()