# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\2173452100291\Documents\OEE_project\UI\UI_file\Sync_missing_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sync_Missing_Data(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(369, 404)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame_sync_missing_data")
        self.frame.setStyleSheet("#frame_sync_missing_data {\n"
                                "    background-color: #f0f0f0;\n" \
                                "    border: 1px solid rgb(86, 214, 246);\n"
                                "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.data_table = QtWidgets.QTableView(self.frame)
        self.data_table.setObjectName("data_table")
        self.verticalLayout.addWidget(self.data_table)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Confirm_btn = QtWidgets.QPushButton(self.frame_3)
        self.Confirm_btn.setObjectName("Confirm_btn")
        self.horizontalLayout_2.addWidget(self.Confirm_btn)
        self.Cancel_btn = QtWidgets.QPushButton(self.frame_3)
        self.Cancel_btn.setObjectName("Cancel_btn")
        self.horizontalLayout_2.addWidget(self.Cancel_btn)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Missing Data"))
        self.label_2.setText(_translate("Form", "Line:"))
        self.Confirm_btn.setText(_translate("Form", "Confirm"))
        self.Cancel_btn.setText(_translate("Form", "Cancel"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Sync_Missing_Data()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
